// React 19 mock for testing

// Re-export everything from React with named exports
export {
  Children,
  Component,
  cloneElement,
  createContext,
  createElement,
  Fragment,
  forwardRef,
  isValidElement,
  lazy,
  memo,
  PureComponent,
  StrictMode,
  Suspense,
  startTransition,
  useCallback,
  useContext,
  useDebugValue,
  useDeferredValue,
  useEffect,
  useId,
  useImperativeHandle,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition,
  version,
} from "react";
