#!/usr/bin/env tsx
/**
 * Post-Code Generation Hook
 * Executes after code is generated by Cline
 * Runs validation, formatting, and integration checks
 *
 * Usage: Run automatically by Cline or manually via: npx tsx cline-hooks/post-code-generation.ts
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

interface GenerationResult {
  filePath: string;
  language: string;
  linesAdded: number;
  timestamp: string;
}

function formatCode(filePath: string): boolean {
  try {
    console.log("✨ Formatting code with Prettier...");
    execSync(`npx prettier --write "${filePath}"`, { stdio: "inherit" });
    console.log("✅ Code formatting complete");
    return true;
  } catch (error) {
    console.error("❌ Code formatting failed");
    return false;
  }
}

function validateImports(filePath: string): boolean {
  try {
    console.log("🔍 Validating imports...");
    execSync(`npx tsc --noEmit --skipLibCheck "${filePath}"`, {
      stdio: "inherit",
    });
    console.log("✅ Import validation passed");
    return true;
  } catch (error) {
    console.error("❌ Import validation failed");
    return false;
  }
}

function checkComponentStructure(filePath: string): boolean {
  const content = fs.readFileSync(filePath, "utf-8");

  // Check for React component patterns
  if (content.includes("export default") || content.includes("export function")) {
    console.log("✅ Component export structure valid");
    return true;
  }

  // Check for TypeScript interfaces/types
  if (content.includes("interface") || content.includes("type ")) {
    console.log("✅ TypeScript types found");
  }

  return true;
}

function updateComponentIndex(filePath: string): void {
  const componentsDir = path.join(process.cwd(), "client", "components");
  const relativePath = path.relative(componentsDir, filePath);

  if (filePath.includes("components") && !relativePath.includes("/")) {
    const indexFile = path.join(componentsDir, "index.ts");
    const componentName = path.basename(filePath, path.extname(filePath));

    if (fs.existsSync(indexFile)) {
      let indexContent = fs.readFileSync(indexFile, "utf-8");

      // Check if already exported
      if (!indexContent.includes(`export * from './${componentName}'`)) {
        indexContent += `\nexport * from './${componentName}';\n`;
        fs.writeFileSync(indexFile, indexContent);
        console.log(`📝 Updated components index with ${componentName}`);
      }
    }
  }
}

function logGenerationResult(result: GenerationResult): void {
  const logDir = path.join(process.cwd(), ".cline", "logs");

  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir, { recursive: true });
  }

  const logFile = path.join(logDir, "generation-log.json");
  const logs = fs.existsSync(logFile)
    ? JSON.parse(fs.readFileSync(logFile, "utf-8"))
    : [];

  logs.push({
    type: "code_generation",
    ...result,
  });

  fs.writeFileSync(logFile, JSON.stringify(logs, null, 2));
}

async function main() {
  const result: GenerationResult = {
    filePath: process.argv[2] || "",
    language: process.argv[3] || "typescript",
    linesAdded: parseInt(process.argv[4] || "0", 10),
    timestamp: new Date().toISOString(),
  };

  if (!result.filePath) {
    console.error("❌ No file path provided");
    process.exit(1);
  }

  console.log("✅ Cline Post-Code Generation Hook");
  console.log("==================================");
  console.log(`📄 Generated file: ${result.filePath}`);
  console.log(`🔤 Language: ${result.language}`);
  console.log(`➕ Lines added: ${result.linesAdded}`);

  // Run validation checks
  const checks = [
    { name: "Code Formatting", fn: () => formatCode(result.filePath) },
    { name: "Import Validation", fn: () => validateImports(result.filePath) },
    { name: "Component Structure", fn: () => checkComponentStructure(result.filePath) },
  ];

  let allPassed = true;

  for (const check of checks) {
    console.log(`\n${check.name}...`);
    const passed = await check.fn();
    if (!passed) {
      allPassed = false;
      break;
    }
  }

  // Update component index if needed
  updateComponentIndex(result.filePath);

  // Log result
  logGenerationResult(result);

  if (allPassed) {
    console.log("\n✅ Post-generation validation complete!");
  } else {
    console.log("\n⚠️  Some validation checks failed");
  }
}

main().catch(console.error);