#!/usr/bin/env tsx
/**
 * Pre-Code Generation Hook
 * Executes before code is generated by Cline
 *
 * Usage: Run automatically by Cline or manually via: npx tsx cline-hooks/pre-code-generation.ts
 */

import * as fs from "fs";
import * as path from "path";

interface GenerationContext {
  prompt: string;
  filePath: string;
  language: string;
}

function checkFileExists(filePath: string): boolean {
  return fs.existsSync(filePath);
}

function getFileContext(filePath: string): string {
  if (!fs.existsSync(filePath)) return "";

  const content = fs.readFileSync(filePath, "utf-8");
  const lines = content.split("\n");

  // Return first 50 lines as context
  return lines.slice(0, 50).join("\n");
}

function validatePath(filePath: string): { valid: boolean; reason?: string } {
  // Prevent path traversal
  if (filePath.includes("..")) {
    return { valid: false, reason: "Path traversal detected" };
  }

  // Ensure path is within workspace
  const workspace = process.cwd();
  const absolutePath = path.resolve(filePath);

  if (!absolutePath.startsWith(workspace)) {
    return { valid: false, reason: "Path outside workspace" };
  }

  return { valid: true };
}

async function main() {
  const context: GenerationContext = {
    prompt: process.argv[2] || "",
    filePath: process.argv[3] || "",
    language: process.argv[4] || "typescript",
  };

  console.log("🔧 Pre-Code Generation Hook");
  console.log("===========================");
  console.log(`📄 Target: ${context.filePath}`);
  console.log(`🔤 Language: ${context.language}`);

  // Validate path
  const validation = validatePath(context.filePath);
  if (!validation.valid) {
    console.error(`❌ Path validation failed: ${validation.reason}`);
    process.exit(1);
  }

  // Check if file exists and get context
  if (checkFileExists(context.filePath)) {
    console.log(`📝 Existing file detected - will provide context`);
    const contextPreview = getFileContext(context.filePath);
    console.log(`\nContext preview (first 500 chars):`);
    console.log(contextPreview.slice(0, 500));
  } else {
    console.log(`✨ New file will be created`);
  }

  // Check TypeScript configuration
  const tsconfigPath = path.join(process.cwd(), "tsconfig.json");
  if (fs.existsSync(tsconfigPath)) {
    console.log(`✅ TypeScript configuration found`);
  }

  // Check component directory structure
  const componentsDir = path.join(process.cwd(), "client", "components");
  if (fs.existsSync(componentsDir)) {
    const components = fs.readdirSync(componentsDir);
    console.log(
      `📁 Components directory: ${components.length} existing components`,
    );
  }

  console.log("\n✅ Pre-generation checks complete");
}

main().catch(console.error);
