@echo off
REM Unset pnpm environment variables to prevent npm warnings
set PNPM_AUTO_INSTALL_PEERS=
set PNPM_CACHE_DIR=
set PNPM_CHILD_CONCURRENCY=
set PNPM_HOIST_PATTERN=
set PNPM_NETWORK_CONCURRENCY=
set PNPM_PREFER_FROZEN_LOCKFILE=
set PNPM_PUBLIC_HOIST_PATTERN=
set PNPM_STATE_DIR=
set PNPM_STORE_DIR=
set PNPM_VERIFY_DEPS_BEFORE_RUN=
set PNPM_JSR_REGISTRY=
REM Unset NPM_CONFIG equivalents to prevent npm warnings
set NPM_CONFIG_AUTO_INSTALL_PEERS=
set NPM_CONFIG_CACHE_DIR=
set NPM_CONFIG_CHILD_CONCURRENCY=
set NPM_CONFIG_HOIST_PATTERN=
set NPM_CONFIG_NETWORK_CONCURRENCY=
set NPM_CONFIG_PREFER_FROZEN_LOCKFILE=
set NPM_CONFIG_PUBLIC_HOIST_PATTERN=
set NPM_CONFIG_STATE_DIR=
set NPM_CONFIG_STORE_DIR=
set NPM_CONFIG_VERIFY_DEPS_BEFORE_RUN=
set NPM_CONFIG_JSR_REGISTRY=
REM Run the original command
%*