// AWS Amplify DataStore/DynamoDB integration for agent CRUD
// This is a stub for backend route refactoring - models will be generated by Amplify

import type { AgentSchemaType } from './agent-validation'

// In-memory store for development until Amplify models are generated
const agentStore = new Map<string, AgentSchemaType & { id: string; createdAt: string; updatedAt: string }>()

// Example: Save agent
export async function saveAgentToDB(agent: AgentSchemaType) {
  const id = `agent-${Date.now()}-${Math.random().toString(36).slice(2)}`
  const now = new Date().toISOString()
  const savedAgent = { ...agent, id, createdAt: now, updatedAt: now }
  agentStore.set(id, savedAgent)
  return savedAgent
}

// Example: List agents
export async function listAgentsFromDB() {
  return Array.from(agentStore.values())
}

// Example: Update agent
export async function updateAgentInDB(agentId: string, updates: Partial<AgentSchemaType>) {
  const original = agentStore.get(agentId)
  if (!original) throw new Error('Agent not found')
  const updated = { ...original, ...updates, updatedAt: new Date().toISOString() }
  agentStore.set(agentId, updated)
  return updated
}

// Example: Delete agent
export async function deleteAgentFromDB(agentId: string) {
  const original = agentStore.get(agentId)
  if (!original) throw new Error('Agent not found')
  agentStore.delete(agentId)
  return { success: true, id: agentId }
}