/**
 * AWS Amplify Configuration for the frontend
 * This file configures Amplify client for authentication, API, and data
 */

import { Amplify } from 'aws-amplify'

// Import the generated outputs from sandbox deployment
// This file is generated by `amplify sandbox` command
import outputs from '../../amplify_outputs.json'

interface AmplifyOutputs {
  version: string
  auth?: {
    user_pool_id: string
    user_pool_client_id: string
    identity_pool_id: string
  }
  api?: {
    url: string
    region: string
  }
  data?: {
    url: string
    region: string
  }
}

/**
 * Amplify configuration object
 */
const config: Record<string, unknown> = {
  Auth: {
    Cognito: {
      userPoolId: (outputs as unknown as AmplifyOutputs).auth?.user_pool_id || '',
      userPoolClientId: (outputs as unknown as AmplifyOutputs).auth?.user_pool_client_id || '',
      identityPoolId: (outputs as unknown as AmplifyOutputs).auth?.identity_pool_id || '',
      signUpVerificationMethod: 'link',
      loginWith: {
        email: true,
      },
    },
  },
  API: {
    REST: {
      // API Gateway endpoints for Lambda functions
      api: {
        endpoint: (outputs as unknown as AmplifyOutputs).api?.url || '',
        region: (outputs as unknown as AmplifyOutputs).api?.region || 'us-east-1',
      },
    },
    GraphQL: {
      endpoint: (outputs as unknown as AmplifyOutputs).data?.url || '',
      region: (outputs as unknown as AmplifyOutputs).data?.region || 'us-east-1',
      defaultAuthMode: 'userPool',
    },
  },
  DataStore: {
    syncExpressions: [],
  },
}

/**
 * Initialize Amplify with configuration
 */
export function initializeAmplify(): void {
  try {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    Amplify.configure(config, {
      API: {
        GraphQL: {
          headers: async () => ({
            'Content-Type': 'application/json',
          }),
        },
      },
    })
  } catch (_error) {}
}

/**
 * Get Amplify configuration
 */
export function getAmplifyConfig() {
  return config
}

/**
 * Check if Amplify is configured
 */
export function isAmplifyConfigured(): boolean {
  const castOutputs = outputs as unknown as AmplifyOutputs
  return Boolean(castOutputs.auth?.user_pool_id && castOutputs.auth?.user_pool_client_id)
}

// Export the configuration for direct use
export default config
