/**
 * AWS Amplify Configuration for the frontend
 * This file configures Amplify client for authentication, API, and data
 */

import { Amplify } from 'aws-amplify'
import type { ResourcesConfig } from '@aws-amplify/core'

// Import the generated outputs from sandbox deployment
// This file is generated by `amplify sandbox` command
import outputs from '../../amplify_outputs.json'

/**
 * Amplify configuration object
 */
const config: ResourcesConfig = {
  Auth: {
    Cognito: {
      userPoolId: outputs.auth?.user_pool_id || '',
      userPoolClientId: outputs.auth?.user_pool_client_id || '',
      identityPoolId: outputs.auth?.identity_pool_id || '',
      signUpVerificationMethod: 'link',
      loginWith: {
        email: true,
      },
    },
  },
  API: {
    REST: {
      // API Gateway endpoints for Lambda functions
      api: {
        endpoint: outputs.api?.url || '',
        region: outputs.api?.region || 'us-east-1',
      },
    },
    GraphQL: {
      endpoint: outputs.data?.url || '',
      region: outputs.data?.region || 'us-east-1',
      defaultAuthMode: 'userPool',
    },
  },
  DataStore: {
    syncExpressions: [],
  },
}

/**
 * Initialize Amplify with configuration
 */
export function initializeAmplify(): void {
  try {
    Amplify.configure(config, {
      API: {
        GraphQL: {
          headers: async () => ({
            'Content-Type': 'application/json',
          }),
        },
      },
    })
    console.log('[Amplify] Configuration initialized successfully')
  } catch (error) {
    console.error('[Amplify] Failed to initialize configuration:', error)
  }
}

/**
 * Get Amplify configuration
 */
export function getAmplifyConfig(): ResourcesConfig {
  return config
}

/**
 * Check if Amplify is configured
 */
export function isAmplifyConfigured(): boolean {
  return Boolean(
    outputs.auth?.user_pool_id &&
    outputs.auth?.user_pool_client_id
  )
}

// Export the configuration for direct use
export default config